name: .NET CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore App.sln

      - name: Build
        run: dotnet build App.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test App.sln --configuration Release --no-build --logger "trx;LogFileName=test_results.trx"
